# Generated by Django 5.0.4 on 2024-05-12 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_customuser_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='numero_telefono',
            field=models.CharField(default='', max_length=10),
        ),
    ]
