# Generated by Django 5.0.4 on 2024-05-12 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_customuser_numero_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='numero_telefono',
            field=models.CharField(default='', max_length=12),
        ),
    ]
