# Generated by Django 5.0.4 on 2024-05-12 05:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formulariocontacto',
            options={'verbose_name': 'Formulario de Contacto', 'verbose_name_plural': 'Formularios de Contacto'},
        ),
        migrations.RemoveField(
            model_name='formulariocontacto',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='formulariocontacto',
            name='nombres',
        ),
        migrations.AddField(
            model_name='formulariocontacto',
            name='apellidos',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='formulariocontacto',
            name='email',
            field=models.EmailField(default='', max_length=64, validators=[django.core.validators.EmailValidator(message='Ingrese una dirección de correo electrónico válida.')]),
        ),
        migrations.AddField(
            model_name='formulariocontacto',
            name='nombre',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='formulariocontacto',
            name='mensaje',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
